### ISSUE TITLE
Print total discards and flips in the log

### ISSUE THREAD

**Issue by maudineormsby** [blinks/arjuna#3]
It would be nice to have a total discard and flip count at the end.

Technically, the discards count is a proxy for what I really want to know, which is average number of discards to find a card that was executed (whether or not it flipped). So there could be a more detailed way to do this, where we ask if the card was executed and if so calculate the result since the last executed card.

**Comment by blinks** [comment]
Now added to the log like "1d+0f" (for 1 discard and 0 flips before reaching the stop card).
